server:
  port: 8002

spring:
  application:
    name: order-consumer-feign-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #配置優先使用IP位址

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate: DEBUG
