server:
  port: 8001

spring:
  application:
    name: order-consumer-feign-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:7001/eureka/
  instance:
    prefer-ip-address: true #eureka顯示IP位址
    instance-id: consumer

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate: DEBUG
