server:
  port: 8001

spring:
  profiles:
    active: '@profile.active@,@database.profile.active@'

  application:
    name: cloud-payment-service
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.wayne.utils.UpperCasePhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #配置優先使用IP位址

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate: DEBUG