server:
  port: 8004

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waynelai85423/spring-cloud-config-server.git
          search-paths: spring-cloud-config-server
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:7001/eureka/
  instance:
    prefer-ip-address: true #eureka顯示IP位址

