server:
  port: 9090

spring:
  application:
    name: cloud-swagger


spring-cloud:
  payment: ${PAYMENT_HOST:localhost}:${PAYMENT_PORT:8001}
  consumer: ${CONSUMER_HOST:localhost}:${CONSUMER_PORT:8002}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 消費管理
        url: http://${spring-cloud.consumer}/v3/api-docs
      - name: 支付管理
        url: http://${spring-cloud.payment}/v3/api-docs

